Disable some build steps for testing only

diff --git a/.github/workflows/builder.yml b/.github/workflows/builder.yml
--- a/.github/workflows/builder.yml
+++ b/.github/workflows/builder.yml
@@ -44,46 +44,46 @@ jobs:
         with:
           type: ${{ env.BUILD_TYPE }}
 
-      - name: Verify version
-        uses: home-assistant/actions/helpers/verify-version@master
-        with:
-          ignore-dev: true
+      # - name: Verify version
+      #   uses: home-assistant/actions/helpers/verify-version@master
+      #   with:
+      #     ignore-dev: true
 
-  build_python:
-    name: Build PyPi package
-    environment: ${{ needs.init.outputs.channel }}
-    needs: ["init", "build_base"]
-    runs-on: ubuntu-latest
-    if: github.repository_owner == 'home-assistant' && needs.init.outputs.publish == 'true'
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4.1.1
+  # build_python:
+  #   name: Build PyPi package
+  #   environment: ${{ needs.init.outputs.channel }}
+  #   needs: ["init", "build_base"]
+  #   runs-on: ubuntu-latest
+  #   if: github.repository_owner == 'home-assistant' && needs.init.outputs.publish == 'true'
+  #   steps:
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v4.1.1
 
-      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
-        uses: actions/setup-python@v5.0.0
-        with:
-          python-version: ${{ env.DEFAULT_PYTHON }}
+  #     - name: Set up Python ${{ env.DEFAULT_PYTHON }}
+  #       uses: actions/setup-python@v5.0.0
+  #       with:
+  #         python-version: ${{ env.DEFAULT_PYTHON }}
 
-      - name: Download Translations
-        run: python3 -m script.translations download
-        env:
-          LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
+  #     - name: Download Translations
+  #       run: python3 -m script.translations download
+  #       env:
+  #         LOKALISE_TOKEN: ${{ secrets.LOKALISE_TOKEN }}
 
-      - name: Build package
-        shell: bash
-        run: |
-          # Remove dist, build, and homeassistant.egg-info
-          # when build locally for testing!
-          pip install twine build
-          python -m build
+  #     - name: Build package
+  #       shell: bash
+  #       run: |
+  #         # Remove dist, build, and homeassistant.egg-info
+  #         # when build locally for testing!
+  #         pip install twine build
+  #         python -m build
 
-      - name: Upload package
-        shell: bash
-        run: |
-          export TWINE_USERNAME="__token__"
-          export TWINE_PASSWORD="${{ secrets.TWINE_TOKEN }}"
+  #     - name: Upload package
+  #       shell: bash
+  #       run: |
+  #         export TWINE_USERNAME="__token__"
+  #         export TWINE_PASSWORD="${{ secrets.TWINE_TOKEN }}"
 
-          twine upload dist/* --skip-existing
+  #         twine upload dist/* --skip-existing
 
   build_base:
     name: Build ${{ matrix.arch }} base core image
@@ -292,170 +292,170 @@ jobs:
             --cosign \
             --machine "${{ needs.init.outputs.version }}=${{ matrix.machine }}"
 
-  publish_ha:
-    name: Publish version files
-    environment: ${{ needs.init.outputs.channel }}
-    if: github.repository_owner == 'home-assistant'
-    needs: ["init", "build_machine"]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4.1.1
+  # publish_ha:
+  #   name: Publish version files
+  #   environment: ${{ needs.init.outputs.channel }}
+  #   if: github.repository_owner == 'home-assistant'
+  #   needs: ["init", "build_machine"]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v4.1.1
 
-      - name: Initialize git
-        uses: home-assistant/actions/helpers/git-init@master
-        with:
-          name: ${{ secrets.GIT_NAME }}
-          email: ${{ secrets.GIT_EMAIL }}
-          token: ${{ secrets.GIT_TOKEN }}
+  #     - name: Initialize git
+  #       uses: home-assistant/actions/helpers/git-init@master
+  #       with:
+  #         name: ${{ secrets.GIT_NAME }}
+  #         email: ${{ secrets.GIT_EMAIL }}
+  #         token: ${{ secrets.GIT_TOKEN }}
 
-      - name: Update version file
-        uses: home-assistant/actions/helpers/version-push@master
-        with:
-          key: "homeassistant[]"
-          key-description: "Home Assistant Core"
-          version: ${{ needs.init.outputs.version }}
-          channel: ${{ needs.init.outputs.channel }}
+  #     - name: Update version file
+  #       uses: home-assistant/actions/helpers/version-push@master
+  #       with:
+  #         key: "homeassistant[]"
+  #         key-description: "Home Assistant Core"
+  #         version: ${{ needs.init.outputs.version }}
+  #         channel: ${{ needs.init.outputs.channel }}
 
-      - name: Update version file (stable -> beta)
-        if: needs.init.outputs.channel == 'stable'
-        uses: home-assistant/actions/helpers/version-push@master
-        with:
-          key: "homeassistant[]"
-          key-description: "Home Assistant Core"
-          version: ${{ needs.init.outputs.version }}
-          channel: beta
+  #     - name: Update version file (stable -> beta)
+  #       if: needs.init.outputs.channel == 'stable'
+  #       uses: home-assistant/actions/helpers/version-push@master
+  #       with:
+  #         key: "homeassistant[]"
+  #         key-description: "Home Assistant Core"
+  #         version: ${{ needs.init.outputs.version }}
+  #         channel: beta
 
-  publish_container:
-    name: Publish meta container for ${{ matrix.registry }}
-    environment: ${{ needs.init.outputs.channel }}
-    if: github.repository_owner == 'home-assistant'
-    needs: ["init", "build_base"]
-    runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      packages: write
-      id-token: write
-    steps:
-      - name: Checkout the repository
-        uses: actions/checkout@v4.1.1
+  # publish_container:
+  #   name: Publish meta container for ${{ matrix.registry }}
+  #   environment: ${{ needs.init.outputs.channel }}
+  #   if: github.repository_owner == 'home-assistant'
+  #   needs: ["init", "build_base"]
+  #   runs-on: ubuntu-latest
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #     id-token: write
+  #   steps:
+  #     - name: Checkout the repository
+  #       uses: actions/checkout@v4.1.1
 
-      - name: Install Cosign
-        uses: sigstore/cosign-installer@v3.4.0
-        with:
-          cosign-release: "v2.0.2"
+  #     - name: Install Cosign
+  #       uses: sigstore/cosign-installer@v3.4.0
+  #       with:
+  #         cosign-release: "v2.0.2"
 
-      - name: Login to DockerHub
-        uses: docker/login-action@v3.0.0
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Login to DockerHub
+  #       uses: docker/login-action@v3.0.0
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v3.0.0
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Login to GitHub Container Registry
+  #       uses: docker/login-action@v3.0.0
+  #       with:
+  #         registry: ghcr.io
+  #         username: ${{ github.repository_owner }}
+  #         password: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build Meta Image
-        shell: bash
-        run: |
-          export DOCKER_CLI_EXPERIMENTAL=enabled
+  #     - name: Build Meta Image
+  #       shell: bash
+  #       run: |
+  #         export DOCKER_CLI_EXPERIMENTAL=enabled
 
-          function create_manifest() {
-            local tag_l=${1}
-            local tag_r=${2}
+  #         function create_manifest() {
+  #           local tag_l=${1}
+  #           local tag_r=${2}
 
-            for registry in "ghcr.io/home-assistant" "docker.io/homeassistant"
-            do
+  #           for registry in "ghcr.io/home-assistant" "docker.io/homeassistant"
+  #           do
 
-              docker manifest create "${registry}/home-assistant:${tag_l}" \
-                "${registry}/amd64-homeassistant:${tag_r}" \
-                "${registry}/i386-homeassistant:${tag_r}" \
-                "${registry}/armhf-homeassistant:${tag_r}" \
-                "${registry}/armv7-homeassistant:${tag_r}" \
-                "${registry}/aarch64-homeassistant:${tag_r}"
+  #             docker manifest create "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/amd64-homeassistant:${tag_r}" \
+  #               "${registry}/i386-homeassistant:${tag_r}" \
+  #               "${registry}/armhf-homeassistant:${tag_r}" \
+  #               "${registry}/armv7-homeassistant:${tag_r}" \
+  #               "${registry}/aarch64-homeassistant:${tag_r}"
 
-              docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-                "${registry}/amd64-homeassistant:${tag_r}" \
-                --os linux --arch amd64
+  #             docker manifest annotate "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/amd64-homeassistant:${tag_r}" \
+  #               --os linux --arch amd64
 
-              docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-                "${registry}/i386-homeassistant:${tag_r}" \
-                --os linux --arch 386
+  #             docker manifest annotate "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/i386-homeassistant:${tag_r}" \
+  #               --os linux --arch 386
 
-              docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-                "${registry}/armhf-homeassistant:${tag_r}" \
-                --os linux --arch arm --variant=v6
+  #             docker manifest annotate "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/armhf-homeassistant:${tag_r}" \
+  #               --os linux --arch arm --variant=v6
 
-              docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-                "${registry}/armv7-homeassistant:${tag_r}" \
-                --os linux --arch arm --variant=v7
+  #             docker manifest annotate "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/armv7-homeassistant:${tag_r}" \
+  #               --os linux --arch arm --variant=v7
 
-              docker manifest annotate "${registry}/home-assistant:${tag_l}" \
-                "${registry}/aarch64-homeassistant:${tag_r}" \
-                --os linux --arch arm64 --variant=v8
+  #             docker manifest annotate "${registry}/home-assistant:${tag_l}" \
+  #               "${registry}/aarch64-homeassistant:${tag_r}" \
+  #               --os linux --arch arm64 --variant=v8
 
-              docker manifest push --purge "${registry}/home-assistant:${tag_l}"
-              cosign sign --yes "${registry}/home-assistant:${tag_l}"
+  #             docker manifest push --purge "${registry}/home-assistant:${tag_l}"
+  #             cosign sign --yes "${registry}/home-assistant:${tag_l}"
 
-            done
-          }
+  #           done
+  #         }
 
-          function validate_image() {
-            local image=${1}
-            if ! cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-identity-regexp https://github.com/home-assistant/core/.* "${image}"; then
-              echo "Invalid signature!"
-              exit 1
-            fi
-          }
+  #         function validate_image() {
+  #           local image=${1}
+  #           if ! cosign verify --certificate-oidc-issuer https://token.actions.githubusercontent.com --certificate-identity-regexp https://github.com/home-assistant/core/.* "${image}"; then
+  #             echo "Invalid signature!"
+  #             exit 1
+  #           fi
+  #         }
 
-          function push_dockerhub() {
-            local image=${1}
-            local tag=${2}
+  #         function push_dockerhub() {
+  #           local image=${1}
+  #           local tag=${2}
 
-            docker tag "ghcr.io/home-assistant/${image}:${tag}" "docker.io/homeassistant/${image}:${tag}"
-            docker push "docker.io/homeassistant/${image}:${tag}"
-            cosign sign --yes "docker.io/homeassistant/${image}:${tag}"
-          }
+  #           docker tag "ghcr.io/home-assistant/${image}:${tag}" "docker.io/homeassistant/${image}:${tag}"
+  #           docker push "docker.io/homeassistant/${image}:${tag}"
+  #           cosign sign --yes "docker.io/homeassistant/${image}:${tag}"
+  #         }
 
-          # Pull images from github container registry and verify signature
-          docker pull "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
-          docker pull "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
+  #         # Pull images from github container registry and verify signature
+  #         docker pull "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
+  #         docker pull "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
+  #         docker pull "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
+  #         docker pull "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
+  #         docker pull "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
 
-          validate_image "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
-          validate_image "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
+  #         validate_image "ghcr.io/home-assistant/amd64-homeassistant:${{ needs.init.outputs.version }}"
+  #         validate_image "ghcr.io/home-assistant/i386-homeassistant:${{ needs.init.outputs.version }}"
+  #         validate_image "ghcr.io/home-assistant/armhf-homeassistant:${{ needs.init.outputs.version }}"
+  #         validate_image "ghcr.io/home-assistant/armv7-homeassistant:${{ needs.init.outputs.version }}"
+  #         validate_image "ghcr.io/home-assistant/aarch64-homeassistant:${{ needs.init.outputs.version }}"
 
-          # Upload images to dockerhub
-          push_dockerhub "amd64-homeassistant" "${{ needs.init.outputs.version }}"
-          push_dockerhub "i386-homeassistant" "${{ needs.init.outputs.version }}"
-          push_dockerhub "armhf-homeassistant" "${{ needs.init.outputs.version }}"
-          push_dockerhub "armv7-homeassistant" "${{ needs.init.outputs.version }}"
-          push_dockerhub "aarch64-homeassistant" "${{ needs.init.outputs.version }}"
+  #         # Upload images to dockerhub
+  #         push_dockerhub "amd64-homeassistant" "${{ needs.init.outputs.version }}"
+  #         push_dockerhub "i386-homeassistant" "${{ needs.init.outputs.version }}"
+  #         push_dockerhub "armhf-homeassistant" "${{ needs.init.outputs.version }}"
+  #         push_dockerhub "armv7-homeassistant" "${{ needs.init.outputs.version }}"
+  #         push_dockerhub "aarch64-homeassistant" "${{ needs.init.outputs.version }}"
 
-          # Create version tag
-          create_manifest "${{ needs.init.outputs.version }}" "${{ needs.init.outputs.version }}"
+  #         # Create version tag
+  #         create_manifest "${{ needs.init.outputs.version }}" "${{ needs.init.outputs.version }}"
 
-          # Create general tags
-          if [[ "${{ needs.init.outputs.version }}" =~ d ]]; then
-            create_manifest "dev" "${{ needs.init.outputs.version }}"
-          elif [[ "${{ needs.init.outputs.version }}" =~ b ]]; then
-            create_manifest "beta" "${{ needs.init.outputs.version }}"
-            create_manifest "rc" "${{ needs.init.outputs.version }}"
-          else
-            create_manifest "stable" "${{ needs.init.outputs.version }}"
-            create_manifest "latest" "${{ needs.init.outputs.version }}"
-            create_manifest "beta" "${{ needs.init.outputs.version }}"
-            create_manifest "rc" "${{ needs.init.outputs.version }}"
+  #         # Create general tags
+  #         if [[ "${{ needs.init.outputs.version }}" =~ d ]]; then
+  #           create_manifest "dev" "${{ needs.init.outputs.version }}"
+  #         elif [[ "${{ needs.init.outputs.version }}" =~ b ]]; then
+  #           create_manifest "beta" "${{ needs.init.outputs.version }}"
+  #           create_manifest "rc" "${{ needs.init.outputs.version }}"
+  #         else
+  #           create_manifest "stable" "${{ needs.init.outputs.version }}"
+  #           create_manifest "latest" "${{ needs.init.outputs.version }}"
+  #           create_manifest "beta" "${{ needs.init.outputs.version }}"
+  #           create_manifest "rc" "${{ needs.init.outputs.version }}"
 
-            # Create series version tag (e.g. 2021.6)
-            v="${{ needs.init.outputs.version }}"
-            create_manifest "${v%.*}" "${{ needs.init.outputs.version }}"
-          fi
+  #           # Create series version tag (e.g. 2021.6)
+  #           v="${{ needs.init.outputs.version }}"
+  #           create_manifest "${v%.*}" "${{ needs.init.outputs.version }}"
+  #         fi
